### ISSUE TITLE
TEST SCENARIO: CDN / offline stuff.

### ISSUE THREAD

**Issue by ryan-roemer** [walmartlabs/little-loader#6]
### Tasks

* [ ] Test CDN resouces: jQuery, Underscore
    * [ ] HTTP URL
    * [ ] HTTPS URL
    * [ ] Protocol-independent URL
    * [ ] Have `test/func/spec/online.spec.js` scenario that can be disabled for offline tests.

### Done

* [x] Test other port-served scripts.
* [ ] ~~Test "previous version" of little loader from CDN~~ ( **On second thought, let's not do this** )

/cc @exogen

**Comment by exogen** [comment]
Capturing this here instead of the other PR: We could avoid requiring network connectivity by just spinning up multiple local HTTP servers, so that we can load our local test scripts from different ports (== different origin).

But I do like the CDN test either way since it's the ultimate real-world scenario.

**Comment by ryan-roemer** [comment]
@Maciek416 @geekdave -- Does magellan provide "another non-conflicting port" besides `FUNC_PORT` that we could spin up a separate static server on locally?

**Comment by Maciek416** [comment]
By default there's a 3 port block per worker:

```
FUNC_PORT = mocking port
FUNC_PORT + 1 = local selenium port (unused in sauce builds)
FUNC_PORT + 2 = second mocking port
```

All are checked for freeness before a worker goes to work
